pipeline {
    agent any

    environment {
        GITHUB_URL = 'https://github.com/Netra-Development-Solutions/Platform.DomainModel'
        GITHUB_BRANCH = 'RELEASE'   
    }
    
    stages {
        stage("Code") {
            steps {
                echo "Cloning the code from GitHub"
                git branch: "${GITHUB_BRANCH}", url: "${GITHUB_URL}"
            }
        }
        stage("Install Dependencies") {
            steps {
                dir("platform-schema-mapper-engine-lib") {
                    echo "Installing npm dependencies"
                    bat "npm install"
                }
            }
        }
        stage("Build module") {
            steps {
                dir("platform-schema-mapper-engine-lib") {
                    echo "Building library"
                    bat "npm run build"
                }
            }
        }
        stage("Run Tests") {
            steps {
                echo "Running tests"
                // bat "npm test"
            }
        }
        stage("Publishing package to NPM") {
            steps {
                dir("platform-schema-mapper-engine-lib") {
                    echo "Publishing package to NPM"
                    withCredentials([string(credentialsId: 'nodejs_authentication_token', variable: 'NPM_TOKEN')]) {
                        bat "npm config set //registry.npmjs.org/:_authToken=%NPM_TOKEN%"
                        bat "npm publish --access=public"
                    }
                }
            }
        }
    }
}